name: "Slinky Link Checker"
description: "Slink through your repository looking for dead links"
author: "LukeHagar"
branding:
  icon: "link"
  color: "blue"

inputs:
  path:
    description: "Root path to scan"
    required: false
    default: "."
  patterns:
    description: "Comma-separated doublestar patterns. Ex: docs/**/*.md,**/*.go; default **/*"
    required: false
    default: "**/*"
  concurrency:
    description: "Maximum concurrent requests"
    required: false
    default: "16"
  timeout:
    description: "HTTP timeout seconds"
    required: false
    default: "10"
  json-out:
    description: "Optional path to write JSON results"
    required: false
    default: "results.json"
  md-out:
    description: "Optional path to write Markdown report for PR comment"
    required: false
    default: "results.md"
  repo-blob-base:
    description: "Override GitHub blob base URL (https://github.com/<owner>/<repo>/blob/<sha>)"
    required: false
    default: ""
  fail-on-failures:
    description: "Fail the job if any links fail"
    required: false
    default: "true"
  comment-pr:
    description: "If running on a PR, post a comment with the report"
    required: false
    default: "true"
  step-summary:
    description: "Append the report to the GitHub Step Summary"
    required: false
    default: "true"

runs:
  using: "docker"
  image: "Dockerfile"
  args: []
  env:
    INPUT_PATH: ${{ inputs.path }}
    INPUT_PATTERNS: ${{ inputs.patterns }}
    INPUT_CONCURRENCY: ${{ inputs.concurrency }}
    INPUT_TIMEOUT: ${{ inputs.timeout }}
    INPUT_JSON_OUT: ${{ inputs["json-out"] }}
    INPUT_MD_OUT: ${{ inputs["md-out"] }}
    INPUT_REPO_BLOB_BASE: ${{ inputs["repo-blob-base"] }}
    INPUT_FAIL_ON_FAILURES: ${{ inputs["fail-on-failures"] }}
    INPUT_COMMENT_PR: ${{ inputs["comment-pr"] }}
    INPUT_STEP_SUMMARY: ${{ inputs["step-summary"] }}

outputs:
  json-path:
    description: "Path to JSON results file"
  md-path:
    description: "Path to Markdown report file"


