name: Slinky Example

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  slinky:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Slinky link checker
        uses: ./

      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: slinky-results
          path: |
            results.json
            results.md


